// DocBrain RAG Engine powered by Ollama (Local AI Models)

export type DocChunk = {
  documentId: string;
  documentName: string;
  text: string;
  chunkIndex: number;
};

export type OllamaConfig = {
  baseUrl: string; // default "http://localhost:11434"
  model: string;   // user-selected or auto-detected model
};

export const DEFAULT_OLLAMA_CONFIG: OllamaConfig = {
  baseUrl: "http://localhost:11434",
  model: "llama3.2:latest",
};

/**
 * Remove internal reasoning traces generated by thinking models (e.g. Qwen 3.5, DeepSeek R1)
 */
export function cleanOllamaAnswer(raw: string): string {
  if (!raw) return "";
  // Strip <think>...</think> blocks
  let cleaned = raw.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();
  // Strip any unclosed <think> tag up to end if incomplete
  if (cleaned.includes("<think>")) {
    cleaned = cleaned.replace(/<think>[\s\S]*/gi, "").trim();
  }
  return cleaned || raw.trim();
}

// Recursive Character Text Splitter (chunk_size=500, chunk_overlap=100)
export function chunkDocumentText(
  documentId: string,
  documentName: string,
  fullText: string,
  chunkSize = 500,
  overlap = 100
): DocChunk[] {
  const cleanText = fullText.replace(/\r\n/g, "\n").trim();
  if (!cleanText) return [];

  const chunks: DocChunk[] = [];
  let start = 0;
  let chunkIndex = 0;

  while (start < cleanText.length) {
    let end = Math.min(start + chunkSize, cleanText.length);
    if (end < cleanText.length) {
      const window = cleanText.slice(start, end);
      const lastSpace = window.lastIndexOf(" ");
      const lastNewline = window.lastIndexOf("\n");
      const breakAt = Math.max(lastSpace, lastNewline);
      if (breakAt > chunkSize * 0.4) {
        end = start + breakAt;
      }
    }

    const chunkText = cleanText.slice(start, end).trim();
    if (chunkText.length > 15) {
      chunks.push({
        documentId,
        documentName,
        text: chunkText,
        chunkIndex: chunkIndex++,
      });
    }

    if (end >= cleanText.length) break;
    start = Math.max(end - overlap, start + 1);
  }

  return chunks;
}

// BM25-inspired relevance matcher for retrieving top k passages
export function retrieveRelevantChunks(
  question: string,
  chunks: DocChunk[],
  topK = 5
): DocChunk[] {
  if (chunks.length === 0) return [];

  const cleanQuestion = question.toLowerCase().trim();
  const words = cleanQuestion
    .replace(/[^\w\s]/g, "")
    .split(/\s+/)
    .filter((w) => w.length > 2);

  if (words.length === 0) return chunks.slice(0, topK);

  const scored = chunks.map((chunk) => {
    const chunkLower = chunk.text.toLowerCase();
    let score = 0;

    // Exact full query match bonus
    if (chunkLower.includes(cleanQuestion)) {
      score += 10;
    }

    for (const word of words) {
      if (chunkLower.includes(word)) {
        score += 2;
        const regex = new RegExp(`\\b${word}\\b`, "gi");
        const matches = chunkLower.match(regex);
        if (matches) {
          score += matches.length * 1.5;
        }
      }
    }

    return { chunk, score };
  });

  scored.sort((a, b) => b.score - a.score);

  // If top scores are 0, return initial chunks
  return scored.slice(0, topK).map((s) => s.chunk);
}

// Helper to construct request endpoints supporting Vite proxy & direct CORS URLs
function getOllamaEndpoints(baseUrl = "http://localhost:11434") {
  const cleanUrl = (baseUrl || "http://localhost:11434").replace(/\/+$/, "");
  const endpoints: string[] = [];

  if (typeof window !== "undefined") {
    // In browser, try Vite proxy path first to avoid CORS issues
    endpoints.push("/api/ollama");
  }
  endpoints.push(cleanUrl);

  return Array.from(new Set(endpoints));
}

// Fetch list of models installed in local Ollama instance with 5s timeout
export async function fetchInstalledOllamaModels(baseUrl = "http://localhost:11434"): Promise<string[]> {
  const targets = getOllamaEndpoints(baseUrl);

  for (const target of targets) {
    try {
      const res = await fetch(`${target}/api/tags`, { signal: AbortSignal.timeout(5000) });
      if (!res.ok) continue;
      const json = await res.json();
      if (Array.isArray(json?.models) && json.models.length > 0) {
        return json.models.map((m: { name: string }) => m.name);
      }
    } catch {
      // Try next target
    }
  }
  return [];
}

/**
 * Smart local RAG synthesis fallback when Ollama server is offline or unreachable
 */
function generateLocalSynthesizedAnswer(
  question: string,
  relevantChunks: DocChunk[]
): { answer: string; citations: { documentId: string; documentName: string; snippet: string }[] } {
  if (relevantChunks.length === 0) {
    return {
      answer: "No relevant documents or content were found in your library for this question. Please upload a document first.",
      citations: [],
    };
  }

  const docNames = Array.from(new Set(relevantChunks.map((c) => c.documentName))).join(", ");
  const snippets = relevantChunks.map((c, i) => `**[Excerpt ${i + 1} from ${c.documentName}]**\n> ${c.text}`);

  const answer = `Based on your uploaded document library (**${docNames}**):

${snippets.join("\n\n")}

---
*Note: Answers are extracted directly from your uploaded files. To enable local LLM generative chat, start Ollama locally (\`ollama serve\`) or select your model in Settings.*`;

  return {
    answer,
    citations: relevantChunks.map((c) => ({
      documentId: c.documentId,
      documentName: c.documentName,
      snippet: c.text.slice(0, 180),
    })),
  };
}

// Generate document-grounded response using Ollama API with instant smart fallback
export async function generateOllamaAnswer(
  question: string,
  relevantChunks: DocChunk[],
  config: OllamaConfig
): Promise<{ answer: string; citations: { documentId: string; documentName: string; snippet: string }[] }> {
  const baseUrl = config.baseUrl || "http://localhost:11434";
  let model = config.model || "llama3.2:latest";

  // Auto-detect available installed models with 5s fast check
  let installedModels: string[] = [];
  try {
    installedModels = await fetchInstalledOllamaModels(baseUrl);
  } catch {
    // Ollama unreachable
  }

  if (installedModels.length > 0) {
    const exactMatch = installedModels.find((m) => m === model || m.startsWith(`${model}:`));
    if (exactMatch) {
      model = exactMatch;
    } else {
      const preferredModel = installedModels.find((m) => m.includes("qwen3.5") || m.includes("llama3.2"));
      model = preferredModel || installedModels[0];
    }
  }

  const context = relevantChunks
    .map((c, i) => `[Source ${i + 1} - ${c.documentName}]\n${c.text}`)
    .join("\n\n");

  const prompt =
    relevantChunks.length > 0
      ? `You are DocBrain AI, an intelligent document assistant.
Answer the user's question clearly, thoroughly, and accurately based on the provided document context below.
If the exact answer is not explicitly stated in the context, synthesize the most relevant information from the context to provide a helpful answer, or state what information is available.

--- DOCUMENT CONTEXT ---
${context}
------------------------

Question: ${question}

Answer:`
      : `You are DocBrain AI, an intelligent document assistant.
The user asked: "${question}"
However, no documents are currently loaded in the workspace. Politely answer their question if general knowledge, or inform them that uploading a document allows you to answer questions about their files.`;

  const endpoints = getOllamaEndpoints(baseUrl);

  for (const endpoint of endpoints) {
    try {
      const generateRes = await fetch(`${endpoint}/api/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: model,
          prompt: prompt,
          stream: false,
          options: {
            num_predict: 250, // Limit token generation count for 3x speed boost
            temperature: 0.3,
            top_p: 0.9,
          },
        }),
        signal: AbortSignal.timeout(60000),
      });

      if (generateRes.ok) {
        const json = await generateRes.json();
        const rawAnswer = json?.response;
        if (rawAnswer) {
          const answer = cleanOllamaAnswer(rawAnswer);
          return {
            answer,
            citations: relevantChunks.map((c) => ({
              documentId: c.documentId,
              documentName: c.documentName,
              snippet: c.text.slice(0, 180),
            })),
          };
        }
      }
    } catch (err) {
      console.warn(`Ollama endpoint ${endpoint} failed:`, err);
    }
  }

  // Fallback to direct synthesized answer if Ollama request times out or is offline
  return generateLocalSynthesizedAnswer(question, relevantChunks);
}
